name: Deploy to Staging

on:
  push:
    branches: [develop]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: cd web && pnpm build

      - name: Run smoke tests
        run: cd web && pnpm test:smoke
        env:
          BASE_URL: ${{ secrets.STAGING_URL }}

      - name: Deploy to staging
        run: |
          # Add your deployment commands here
          # Example: rsync, docker push, etc.
          echo "Deploying to staging environment"
          # Replace with actual deployment logic

  notify:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: always()

    steps:
      - name: Notify on failure
        if: failure()
        run: |
          echo "Deployment to staging failed"
          # Add notification logic (Slack, Discord, etc.)
